### Test the server
GET http://127.0.0.1:5000

### Test register endpoint
POST  http://127.0.0.1:5000/auth/register
Content-Type: application/json

{
  "username": "smitpehghtzfgfgdkehgr34",
  "password": "123456",
  "name": "Smit Petfer"
}

### Test login endpoint
POST http://127.0.0.1:5000/auth/login
Content-Type: application/json

{
  "username": "smitpeter777@gmail.com",
  "password": "123456789"
}

### Test verification endpoint
GET http://127.0.0.1:5000/auth/verification
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyOSwiZXhwIjoxNzM1MTQyNjIzfQ.G4Fp9l3Qs24huIOhCzSGzpM-dOiZ8QErC85uNNQwJbk


### Test stock price endpointf
GET http://127.0.0.1:5000/stock/history-price?stock_symbol=ACHR&start=2024-01-01&end=2024-12-24
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyOSwiZXhwIjoxNzM1MTQ5MDg0fQ.9vcvHXZTv2RKMrmW1BVg88VT4vmEa_I8nBK0mU7XO7U

### Test create-portfolio
POST http://127.0.0.1:5000/stock/create-portfolio
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0MSwiZXhwIjoxNzM1NDkzNTg0fQ.jshG-19sNXKoWKI09baHXzSxTnX0d0En9ZP-6rjJpfk

{
  "name": "portfolio név",
  "description": "Leírása"
}

### Test add-share-to portfolio

POST http://127.0.0.1:5000/stock/add-shares-to-portfolio
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0MSwiZXhwIjoxNzM1NTUxNzg0fQ.rXBPqbYvqwF1MZ3OHCvLtjWYdxXQpZqVyLhc19pCZ5U
Content-Type: application/json

{
  "portfolio_id": 20,
  "share_data": [
    {
      "share_id": "TEST",
      "cost_value": 150.25,
      "quantity": 10,
      "date": "2024-12-27"
    }
  ]
}
### Get user portfolios
GET http://localhost:5000/stock/get-user-portfolios
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0MSwiZXhwIjoxNzM1NTU4NDkxfQ.AQlKLA4R5CewV4XjcFn2xdvzoYzvaov6EzTsqQkytOc

### Get shares for portfolio

GET http://localhost:5000/stock/get-shares-for-portfolio?portfolio_id=21
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0MSwiZXhwIjoxNzM1NTU4NDkxfQ.AQlKLA4R5CewV4XjcFn2xdvzoYzvaov6EzTsqQkytOc


### Delete portfolio

DELETE http://localhost:5000/stock/delete-portfolio?portfolio_id=1

Authorization: Bearer <token>

### Delete share from portfolio

DELETE http://localhost:5000/stock/delete-share-from-portfolio?portfolio_id=3&share_id=4
Authorization: Bearer <token>