services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - BACKEND_URL=http://backend:5000
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DATABASE_PATH=/data/portfolio.db
    volumes:
      - ./data:/data  # Lokális data mappa mountolása a backend konténerhez
    networks:
      - app-network

networks:
  app-network:
