### Test the server
GET http://127.0.0.1:5000

### Test register endpoint
POST http://127.0.0.1:5000/register
Content-Type: application/json

{
  "username": "tesztggelek",
  "password": "123456"
}

### Test login endpoint
POST http://127.0.0.1:5000/login
Content-Type: application/json

{
  "username": "tesztggelek",
  "password": "123456"
}

### Test login endpoint
GET http://127.0.0.1:5000/protected
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxNywiZXhwIjoxNzM0OTk1Mjg1fQ.u4SbFH2p0n-n0JbAiNEXaKYHK3YqirFrxZ5VPsBelf8



