version: '3.8'

services:
  flask-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask-backend
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - FLASK_ENV=development

  mongodb:
    image: mongo
    container_name: mongodb-container
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
