name: Docker Compose Full Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Kód ellenőrzése
      - name: Checkout code
        uses: actions/checkout@v3

      # Docker Compose elindítása
      - name: Start Docker Compose
        run: docker-compose up -d

      # Backend tesztelése
      - name: Test Backend
        run: |
          docker-compose exec backend pytest  # Például a backend tesztjeihez
        continue-on-error: false

      # Frontend állapotának ellenőrzése
      - name: Check Frontend Health
        run: curl -f http://localhost:3000 || exit 1

      # Opcionális: Frontend tesztek (például Cypress vagy más tesztkeret)
      - name: Run Frontend Tests
        run: |
          docker-compose exec frontend npm run test
        continue-on-error: false

      # Docker Compose konténerek leállítása
      - name: Cleanup
        run: docker-compose down
